//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::joayo::Entity as Joayo;
pub use super::password_identity::Entity as PasswordIdentity;
pub use super::session::Entity as Session;
pub use super::upload_result::Entity as UploadResult;
pub use super::user::Entity as User;
